# Generated by Django 2.2.3 on 2019-11-08 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191108_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Level'),
        ),
    ]
