# Generated by Django 2.2.3 on 2019-09-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='ToDo',
        ),
    ]
