# Generated by Django 2.2.3 on 2019-09-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190920_1911'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDo',
            new_name='List',
        ),
    ]
