# Generated by Django 2.2.3 on 2019-09-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190921_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='posted_date',
        ),
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
