# Generated by Django 2.2.3 on 2019-09-22 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_auto_20190922_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
