# Generated by Django 2.2.3 on 2020-03-15 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0006_borrower_issued_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
