# Generated by Django 2.2.3 on 2020-03-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0007_auto_20200315_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
