# Generated by Django 2.2.3 on 2020-03-16 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0009_borrower_returned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='returned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
